config/routes.rb
Rails.application.routes.draw do
  get "upload" => "images#new", :as => "upload"
  get 'images/new'
  get 'images/create'
  get 'images/destroy'
  get 'images/index'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/destroy'
  get 'categories/show'
  resources :images, :categories
  root 'images#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :category
    
    mount_uploader :image, ImageUploader

    before_save :update_image_attributes

    private
    def update_image_attributes
        if image.present? && image_changed?
            self.image_content_type = image.file.content_type
            self.image_file_size = image.file.size
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :getCategoryNav
    
    protect_from_forgery with: :exception

    private
    def getCategoryNav
        @categoryNav = Category.all
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category=Category.new
  end

  def create
    @category=Category.new(category_params)
    if @category.save
      flash[:notice]="Image created"
      redirect_to root_path
    else
      render 'new'
    end  
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice]="Image Updated"
      redirect_to category_path(params[:id])
    else
      render 'edit'
    end  
  end

  def destroy
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end

  def create
    @image=Image.new(image_params)
    if @image.save
      flash[:notice]="Image created"
      redirect_to root_path
    else
      render 'new'
    end  
  end

  def destroy
    @images = Image.find(params[:id])
    @images.destroy

    flash[:notice]="Image Removed"

    redirect_to images_path
  end

  def index
    @images = Image.all
    @categories = Category.all
  end
  private
    def image_params
      params.require(:image).permit(:image, :category_id, :image_title, :image_description, :image_file_size, :image_content_type, :remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_icons_helper.rb
module BootstrapIconsHelper
    # refer https://icons.getbootstrap.com/
    def icon(icon, options = {})
      file = File.read("node_modules/bootstrap-icons/icons/#{icon}.svg")
      doc = Nokogiri::HTML::DocumentFragment.parse file
      svg = doc.at_css 'svg'
      if options[:class].present?
        svg['class'] += " " + options[:class]
      end
        doc.to_html.html_safe
    end
  end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>
<%= form_for @category do |f| %>
    <% if @category.errors.any? %>
       <% @category.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><% msg %></div>  
    <%end%>
<%end%>

<div class="form-grup">
    <%= f.label :name%>
    <%= f.text_field :name, class:'form-control' %>
</div>
<br>
    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%= link_to "Cancel", categories_path, class:'btn btn-default' %>
<%end%>
<h3 class="page-header">Images in <%= @category.name %></h3>
<div id="edit_images">
    <% if @images.exists? %>
        <% if @images.each_slice(6) do |image| %>
            <div class="row">
                <% image.each do |image| %>
                    <div class="col-md-2">
                        <%= image_tag image.image_url(:thumb) %>
                        <center><%= link_to "Delete", image_path(image), class:'delete', method: :delete, data: {confirm: 'Are you sure?'} %></center>
                    </div>
                <%end%>
            </div>
             <%end%>
        <%end%>
    <%end%>
</div>

app/views/categories/new.html.erb
<h2>Add New Category</h2>
<%= form_for @category do |f| %>
    <% if @category.errors.any? %>
       <% @category.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><% msg %></div>  
    <%end%>
<%end%>

<div class="form-grup">
    <%= f.label :name%>
    <%= f.text_field :name, class:'form-control' %>
</div>
<br>
    <%= f.submit "Submit", class:'btn btn-primary' %>
    <%= link_to "Cancel", categories_path, class:'btn btn-default' %>
<%end%>

app/views/categories/show.html.erb
<div id="gallery" class="text-white">
    <h2><%= @category.name %>
      <small class="pull-right"><%= link_to "", edit_category_path %></small>
    </h2>
    <% if @images.exists? %>                            
      <% @images.each_slice(4) do |image| %>
        <div class="row">
          <% image.each do |image| %>
            <div class="col-md-3">
              <div class="photo photo-type-line">
                <a href="<%= image.image.url() %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                <div class="photo-info">
                <div class="headline"><%= image.image_title %></div>
                <div class="line"></div>
                <div class="desc"><%= image.image_description %></div>
              </div>
              <div class="mask"></div>
              </a>
              <div class="photo-img"><%= image_tag image.image.url(:thumb) %></div>
            </div>
          </div>
          <%end%>  
        </div>
      <%end%>  
      <% else %>
        <p>There is no images</p>
    <%end%>
      
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/index.html.erb
     <div class="pricing-header p-3 pb-md-4 mx-auto text-center text-white" id="section2">
        <h1 class="display-4 fw-normal">Portafolio</h1>
      <h5>Hecha un vistazo a nuestra Galleria y proyectos que seguro te encantarán!</h5>
    </div>
  <div id="gallery" >
    <% if @images.exists? %>
      <% @images.each_slice(4) do |image| %>
        <div class="row">
          <% image.each do |image| %>
            <div class="col-md-3">
              <div class="photo photo-type-line">
                <a href="<%= image.image.url() %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                <div class="photo-info">
                <div class="headline"><%= image.image_title %></div>
                <div class="line"></div>
                <div class="desc"><%= image.image_description %></div>
              </div>
              <div class="mask"></div>
              </a>
              <div class="photo-img"><%= image_tag image.image.url(:thumb) %></div>
            </div>
          </div>
          <%end%>  
        </div>
      <%end%>  
      <% else %>
        <p>There is no images</p>
    <%end%>
  </div>  

app/views/images/new.html.erb
<h2>Upload Image</h2>
<%= form_for @image, :html => {:multipart => true} do |f| %>
    <% if @image.errors.any? %>
       <% @image.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%msg%></div>  
       <%end%>
    <%end%>
    <div class="form-grup">
        <%= f.label :image_title %>
        <%= f.text_field :image_title, class:'form-control' %>
    </div>

    <div class="form-grup">
        <%= f.label :category %>
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %>
    </div>

    <div class="form-grup">
        <%= f.label :image_description %>
        <%= f.text_area :image_description, class:'form-control' %>
    </div>

    <div class="form-grup">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>

    <br>
        <%= f.submit "Submit", class:'btn btn-primary' %>
        <%= link_to "Cancel", images_path, class:'btn btn-default' %>
<%end%>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-center text-white">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">Lords//Photography</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_frontpage.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
</svg>
<div class="container_cover text-white ">
<nav class="navbar navbar-expand-md navbar-dark bg-black ">
    <div class="container-fluid nav_hover">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="nav navbar-nav me-auto ">
                <li class="nav-item ">
                    <a class="nav-link" href="#section3">Cotizaciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#section4">Conocenos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#section5">Contactanos</a>
                </li>
                <li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Portafolio </a>
                    <ul class="dropdown-menu dropdown-menu-right bg-dark " aria-labelledby="navbarScrollingDropdown">
                      <% @categoryNav.each do |category| %>
                        <li class="dropdown-item"><%= link_to category.name, category_path(category.id), :class => "nav-link" %></li>
                      <% end %>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="mx-auto order-0">
            <%= link_to "Lords Photography", root_path, :class => "navbar-brand mx-auto" %> 
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <%= link_to "Upload Photo", upload_path, :class => "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Add Category", new_category_path, :class => "nav-link" %>
                </li>
            </ul>
        </div>
        
    </div>
</nav>
    <main class="px-3 mx-auto">
        <h1 class="font_italic h1">Lords Photography.</h1>
        <p class="lead">Lords// es un grupo de
        jóvenes con ideas
        posmodernistas y tendencias
        versátiles, que buscan retratar
        su entorno e ideas, esto utilizando a las
        tecnologías de información,
        su entorno inmediato y a la
        cultura underground como
        principales herramientas.</p>
        <p class="lead"><a href="#section2" class="btn btn-lg btn-secondary fw-bold border-white bg-black">Saber Más</a></p>
</main>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-transparent">
    <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="nav navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#section3">Cotizaciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#section4">Conocenos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#section5">Contactanos</a>
                </li>
                <li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Portafolio </a>
                    <ul class="dropdown-menu dropdown-menu-right bg-dark " aria-labelledby="navbarScrollingDropdown">
                      <% @categoryNav.each do |category| %>
                        <li class="dropdown-item"><%= link_to category.name, category_path(category.id), :class => "nav-link" %></li>
                      <% end %>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="mx-auto order-0">
            <%= link_to "Lords Photography", root_path, :class => "navbar-brand mx-auto" %> 
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <%= link_to "Upload Photo", upload_path, :class => "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Add Category", new_category_path, :class => "nav-link" %>
                </li>
            </ul>
        </div>
        
    </div>
</nav>

app/views/layouts/_services.html.erb
<div class="bg-white" id="section3">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center ">
      <h1 class="display-4 fw-normal">Servicios</h1>
      <p class="fs-5 text-muted">Dejalo en manos de los profesionales. Retrata tus ideas, emociones y mejores momentos con la mejor tecnologia del mercado.</p>
    </div>
<div>
</div>
  <main class="container py-3 ">
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Eventos sociales</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$10000<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Cobertura con equipo profesional</li>
              <li>1 fotógrafo</li>
              <li>50 fotografías impresas en tamaño media carta con retoque</li>
              <li>Cobertura de 3 horas</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Cotizalo Ya!</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Publicidad</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$15000<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Cobertura con equipo profesional</li>
              <li>1 fotógrafo</li>
              <li>100 fotografías impresas en tamaño media carta con retoque</li>
              <li>Cobertura de 6 horas</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Cotizalo Ya!</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
          <div class="card-header py-3 text-white bg-primary border-primary">
            <h4 class="my-0 fw-normal">Corporativas</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$20000<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Cobertura con equipo profesional</li>
              <li>1 fotógrafo</li>
              <li>100 fotografías impresas en tamaño media carta con retoque</li>
              <li>Cobertura de 12 horas hora</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Cotizalo Ya!</button>
          </div>
        </div>
      </div>
    </div>

    <h2 class="display-6 text-center mb-4">Planes y Servicios</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            <th style="width: 22%;">Eventos sociales</th>
            <th style="width: 22%;">Publicidad</th>
            <th style="width: 22%;">Corporativas</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" class="text-start">Álbum personalizado</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Photobook de 10x12 pulgadas </th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>

        <tbody>
          <tr>
            <th scope="row" class="text-start">Fotografías en formato digital</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Fotografías ilimitadas</th>
            <td></td>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>
      </table>
    </div>
  </main>
</div>

app/views/layouts/_teamworker.html.erb
<div class="container_teamworker text-center marketing text-white " id="section4">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center ">
      <h1 class="display-4 fw-normal">Conocenos</h1>
      <h5>Siempre dedicados a lo que nos apasiona, para brindarte el mejor servicio </h5>
    </div>
    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <img src="https://www.sprintcv.com/assets/sprintcv-helps-java-consultant-to-generate-amazing-cv-1228395647dab08deb54ccec4dd549db6477ded6803a1f00ac7fbc499b66555c.jpg" class="bd-placeholder-img rounded-circle" width="140" height="140">
        <h2>Parveen Anand</h2>
        <h3>Lider Directivo</h3>
        
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img src="https://computacioninteractiva.com/wp-content/uploads/2021/01/beautiful-girl-with-afro-hair-min-500x500.jpg" class="bd-placeholder-img rounded-circle" width="140" height="140">
        <h2>Diana Petersen</h2>
        <h3>Fotografa Profesional</h3>
        
      </div>
      <div class="col-lg-4">
        <img src="https://cdn1.photostockeditor.com/t/2612/human-smiling-man-standing-near-green-tree-person-person-image.jpg" class="bd-placeholder-img rounded-circle" width="140" height="140">
        <h2>Larry Parker</h2>
        <h3>Diseñador</h3>
        
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
</div>

<div class="my-md-6 ps-md-6 " id="section5">
    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">Contactanos</h2>
        <p class="lead">Adquiere un experiencia más persolizada.</p>
      </div>
      <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;">
          <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4" style="padding: 50px;">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab bi-facebook" style="font-size: 3rem;"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab bi-whatsapp" style="font-size: 3rem;"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab bi-google" style="font-size: 3rem;"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button" 
        ><i class="fab bi-instagram" style="font-size: 3rem;"></i
      ></a>

    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RGallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>  
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <% if !current_page?(root_url) %>
    <%= render "layouts/navbar"%>
    <%end%>
    
    <% if current_page?(root_url) %>
      <%= render "layouts/frontpage"%>
    <%end%>

    <section>
    <div class="container">
      <% if flash[:notice] %>
         <div class="alert alert-success"><%= flash[:notice]%></div>
      <% end %>
      <% if flash[:alert] %>
          <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>
     <%= yield %>
    </div><!-- /.container -->
    </section>

    <% if current_page?(root_url) %>
      <%= render "layouts/services"%>
    <%end%>
    <div id="tsparticles"></div>
    <% if current_page?(root_url) %>
      <%= render "layouts/teamworker"%>
    <%end%>

    <%= render "layouts/footer"%>
    
    <%= javascript_pack_tag 'lightbox' %>
  </body>
</html>